services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_container
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Coti@2025"
      ACCEPT_EULA: "Y"
    restart: always
    networks:
      - sql_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"  # Porta do RabbitMQ
      - "15672:15672" # Porta da interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    restart: always
    networks:
      - sql_network

networks:
  sql_network:
